language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: YR6TjEShwqXylKQn53m4PBWivYv2uqkCdxceLMYxnX2NsS9zzpcwv4N11LIpVgQTYUEnuW8Sf6Bz99ZHv1A1bzlmv4kK023U/baWhCxdG1qCxuYfwBBQy4O+130UoSrk7c8qFlyLo9qRJ7so4bp+TKxGqN70RU2RKf5eQeKGawWG7oc1UD81zUXdGgDWnDQ7I5xrzYpbQXwtI82CaCDl4xmVBX4FiajUz92bFWl3SI+Xte6SmeWDHIxk5gv4boblSZiJ9m9fYfeleJ0sHvu5mK5qAa9oxRC7tHeLEeU7Wytg/uELyurun+uoq/8jGoo5OfDHA1Ck5pMULdvvOy0xta68hgNy7teR4t5J334ETEoQnC72nWVWvTM+3BC6Orvijc0RZWV0/bM99BLRzMNjovjxgKX+aixc1ZGkjAiqMejljXreuu7WVSGfflkuME4HQ2jY0jJeG1APporLwtQPtRClRaumWQcIafVzFKSWuzzCDaWKJRRJlsIivrrO3oDqJAYkA4OJeJH5UENCspJqZG70c29ZfBflpRXCCfjlaZa4GaYZ9MJzfs/Ngb/iQYqZOFdl+TS5D3Mg1nz1fNRNxySB/gfmaWEZ9c9+3OmI49IlfRFQAo71o3RfNGE/QpzpB9fI9h0fTvUUCQ9WsfC4jlVW5QlnLHlaWz0l9avqI7Q=
